### PR TITLE
Added mods

### PR DESCRIPTION
**Pull request by oooccceeeaaannn**
Added mods

### CODE REVIEW

**Comment by PlasmaFlare** [comment]
Hey. I appreciate you taking the time and effort to make this PR. However due to the massive amount of changes, I'm not taking pull requests to add more mods at this time. I personally don't feel comfortable with reviewing something that has so many changes that it's hard to manage and keep track of as the main dev behind the mega modpack, not to mention adding even more potential for bugs without me having a good grasp on the current state of the modpack.

Sorry for the trouble. But I hope you understand where Im coming from.

**Comment by oooccceeeaaannn** [comment]
ok

**Comment by oooccceeeaaannn** [comment]
can you make a new branch for it?
i can maintain it

**Comment by oooccceeeaaannn** [comment]
In fact, 2896 of the changes are JUST adding image files. Only 101 for the actual lua.

**Comment by PlasmaFlare** [comment]
> can you make a new branch for it?
> i can maintain it

Thats what your fork is for

**Comment by oooccceeeaaannn** [comment]
ok

goodbye

**Pull request closed without merging**
